// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.32/00       [335872]
Creator        : zmao
Date           : Mon Sep  8 04:36:01 2014
Host           : Linux vocms19.cern.ch 2.6.32-358.6.2.el6.x86_64 #1 SMP Thu May 16 21:00:12 CEST 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/hep.wisc.edu/user/zmao/CMSSW_5_3_15/src/TMVA-v4.2.0/test
Training events: 3667
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "100" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
svMass                        svMass                        svMass                        svMass                                                          'F'    [22.9085979462,1469.03637695]
dRTauTau                      dRTauTau                      dRTauTau                      dRTauTau                                                        'F'    [0.503454089165,4.52196025848]
dRJJ                          dRJJ                          dRJJ                          dRJJ                                                            'F'    [0.507872641087,5.18856477737]
svPt                          svPt                          svPt                          svPt                                                            'F'    [1.23204696178,511.655853271]
dRhh                          dRhh                          dRhh                          dRhh                                                            'F'    [0.0995119735599,7.52639436722]
met                           met                           met                           met                                                             'F'    [1.07969033718,324.281097412]
mJJReg                        mJJReg                        mJJReg                        mJJReg                                                          'F'    [31.7132720947,945.108093262]
metTau1DPhi                   metTau1DPhi                   metTau1DPhi                   metTau1DPhi                                                     'F'    [6.68798747938e-05,3.13961219788]
metTau2DPhi                   metTau2DPhi                   metTau2DPhi                   metTau2DPhi                                                     'F'    [0.000290418567602,3.14280724525]
metJ1DPhi                     metJ1DPhi                     metJ1DPhi                     metJ1DPhi                                                       'F'    [0.00385962915607,3.14285540581]
metJ2DPhi                     metJ2DPhi                     metJ2DPhi                     metJ2DPhi                                                       'F'    [0.000325195607729,3.13989162445]
metTauPairDPhi                metTauPairDPhi                metTauPairDPhi                metTauPairDPhi                                                  'F'    [0.000361758517101,3.14291119576]
metSvTauPairDPhi              metSvTauPairDPhi              metSvTauPairDPhi              metSvTauPairDPhi                                                'F'    [0.000301132968161,3.14127850533]
metJetPairDPhi                metJetPairDPhi                metJetPairDPhi                metJetPairDPhi                                                  'F'    [0.00355885387398,3.14213061333]
CSVJ1                         CSVJ1                         CSVJ1                         CSVJ1                                                           'F'    [0.679072499275,1]
CSVJ2                         CSVJ2                         CSVJ2                         CSVJ2                                                           'F'    [0.24412997067,0.999998211861]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "svMass", "dRTauTau", "dRJJ", "svPt", "dRhh", "met", "mJJReg", "metTau1DPhi", "metTau2DPhi", "metJ1DPhi", "metJ2DPhi", "metTauPairDPhi", "metSvTauPairDPhi", "metJetPairDPhi", "CSVJ1", "CSVJ2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.924166816930238);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.871876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.225693,-99) , 
0, 145.83, 1, 0, 0.82862,-99) , 
NN(
0, 
0, 
-1, 78.9596, 0, -1, 0.106754,-99) , 
0, 90.4076, 0, 0, 0.738683,-99) , 
NN(
0, 
0, 
-1, 141.262, 1, -1, 0.0963809,-99) , 
1, 2.14223, 1, 0, 0.4673,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.622559);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.781474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392179,-99) , 
6, 167.986, 1, 0, 0.705501,-99) , 
NN(
0, 
0, 
-1, 81.1856, 0, -1, 0.209717,-99) , 
0, 94.6988, 0, 0, 0.62804,-99) , 
NN(
0, 
0, 
-1, 0.661237, 1, -1, 0.015652,-99) , 
0, 170.887, 1, 0, 0.517801,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.46996);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.37322, 1, 1, 0.708148,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.248608,-99) , 
5, 23.7259, 1, 0, 0.419619,-99) , 
3, 106.487, 0, 0, 0.581394,-99) , 
NN(
0, 
0, 
-1, 0.596578, 1, -1, 0.135745,-99) , 
0, 151.771, 1, 0, 0.466055,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.388806);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303982,-99) , 
6, 147.195, 1, 0, 0.57109,-99) , 
NN(
0, 
0, 
-1, 1.64697, 1, -1, 0.195334,-99) , 
6, 85.9105, 0, 0, 0.517154,-99) , 
NN(
0, 
0, 
-1, 1.31341, 1, -1, 0.0833909,-99) , 
0, 159.993, 1, 0, 0.439869,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.245861);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327884,-99) , 
11, 2.24114, 1, 0, 0.580563,-99) , 
NN(
0, 
0, 
-1, 1.46504, 0, -1, 0.0378876,-99) , 
0, 79.3435, 0, 0, 0.546599,-99) , 
NN(
0, 
0, 
-1, 2.11174, 0, -1, 0.0600313,-99) , 
0, 209.255, 1, 0, 0.505034,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.360894);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358758,-99) , 
6, 103.356, 0, 0, 0.597258,-99) , 
NN(
0, 
0, 
-1, 85.0436, 0, -1, 0.271394,-99) , 
0, 97.6215, 0, 0, 0.513382,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530389,-99) , 
NN(
0, 
0, 
-1, 3.35379, 0, -1, 0.17085,-99) , 
1, 1.78771, 1, 0, 0.228873,-99) , 
0, 133.892, 1, 0, 0.41001,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.200862);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 27.7926, 1, 1, 0.626615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.188545,-99) , 
3, 82.7078, 0, 0, 0.563158,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.836741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378345,-99) , 
15, 0.730889, 0, 0, 0.626755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.112105,-99) , 
10, 2.92397, 0, 0, 0.175367,-99) , 
4, 3.75932, 0, 0, 0.265814,-99) , 
1, 2.05515, 1, 0, 0.44641,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.161975);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.775603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454471,-99) , 
5, 10.0168, 1, 0, 0.478974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 83.5661, 0, 0, 0.45739,-99) , 
NN(
0, 
0, 
-1, 0.343105, 1, -1, 0.148853,-99) , 
5, 71.8066, 1, 0, 0.418615,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.170773);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249439,-99) , 
5, 84.9006, 1, 0, 0.566476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 77.3111, 0, 0, 0.54728,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302344,-99) , 
10, 2.49137, 0, 0, 0.468205,-99) , 
NN(
0, 
0, 
-1, 0.410009, 1, -1, 0.0145083,-99) , 
4, 3.33687, 0, 0, 0.201104,-99) , 
1, 2.84361, 1, 0, 0.498278,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.143217);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.896321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351745,-99) , 
8, 1.07442, 1, 0, 0.776875,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415793,-99) , 
9, 0.813791, 1, 0, 0.473519,-99) , 
0, 178.319, 0, 0, 0.512506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 212.952, 1, 0, 0.484402,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.265086);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329937,-99) , 
14, 0.879602, 0, 0, 0.598951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.275463,-99) , 
5, 20.0261, 1, 0, 0.36995,-99) , 
12, 1.36836, 1, 0, 0.515473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 214.233, 1, 0, 0.489126,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.144467);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.864662,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368264,-99) , 
12, 1.02723, 1, 0, 0.469634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 223.362, 1, 0, 0.449918,-99) , 
11, 3.01845, 0, 0, 0.480869,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.108748);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495175,-99) , 
7, 0.964691, 1, 0, 0.579009,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.113214,-99) , 
9, 1.37489, 1, 0, 0.32334,-99) , 
0, 137.243, 1, 0, 0.498854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 81.731, 0, 0, 0.476199,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.196579);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.786689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383596,-99) , 
5, 50.1037, 1, 0, 0.700738,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167615,-99) , 
11, 0.52337, 0, 0, 0.446703,-99) , 
6, 116.886, 0, 0, 0.565928,-99) , 
NN(
0, 
0, 
-1, 2.44107, 1, -1, 0.229649,-99) , 
6, 158.322, 1, 0, 0.48969,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.104851);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0805597,-99) , 
0, 81.2523, 0, 0, 0.52742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 213.546, 1, 0, 0.511725,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509181,-99) , 
NN(
0, 
0, 
-1, 2.80153, 0, -1, 0.124277,-99) , 
12, 0.214231, 1, 0, 0.195216,-99) , 
5, 71.48, 1, 0, 0.467857,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.12244);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307468,-99) , 
6, 164.62, 1, 0, 0.497179,-99) , 
NN(
0, 
0, 
-1, 1.63682, 1, -1, 0.258803,-99) , 
6, 91.8333, 0, 0, 0.456139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 199.68, 1, 0, 0.432899,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.1337);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321311,-99) , 
2, 1.4418, 0, 0, 0.524717,-99) , 
NN(
0, 
0, 
-1, 104.422, 0, -1, 0.185676,-99) , 
8, 2.64527, 1, 0, 0.485871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 201.506, 1, 0, 0.462038,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.241293);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.836542,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324854,-99) , 
0, 109.609, 0, 0, 0.423473,-99) , 
8, 0.192382, 1, 0, 0.446311,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.727565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.203258,-99) , 
11, 1.09412, 1, 0, 0.40561,-99) , 
NN(
0, 
0, 
-1, 0.990467, 0, -1, 0.134467,-99) , 
13, 1.93274, 1, 0, 0.263981,-99) , 
0, 131.111, 1, 0, 0.381485,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.138054);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432573,-99) , 
8, 0.28195, 1, 0, 0.461861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 81.9614, 0, 0, 0.444725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 180.408, 1, 0, 0.417027,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.109943);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.813489,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.720041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429209,-99) , 
11, 2.08512, 0, 0, 0.485547,-99) , 
NN(
0, 
0, 
-1, 83.898, 0, -1, 0.318249,-99) , 
8, 1.27704, 1, 0, 0.403933,-99) , 
4, 4.39659, 0, 0, 0.426452,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0942485);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.907621,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.856433,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.267286,-99) , 
3, 69.7678, 0, 0, 0.480085,-99) , 
11, 3.04957, 0, 0, 0.500798,-99) , 
5, 7.47972, 1, 0, 0.520876,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.193442);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.226355,-99) , 
3, 38.8535, 0, 0, 0.612104,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652153,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0500275,-99) , 
11, 0.468002, 1, 0, 0.255726,-99) , 
5, 67.4024, 1, 0, 0.571826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.760566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388461,-99) , 
1, 2.16442, 0, 0, 0.567085,-99) , 
NN(
0, 
0, 
-1, 0.467331, 0, -1, 0.285416,-99) , 
15, 0.432602, 1, 0, 0.362007,-99) , 
2, 1.59422, 0, 0, 0.508421,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.09714);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.913309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49172,-99) , 
7, 0.0596945, 0, 0, 0.771972,-99) , 
NN(
0, 
0, 
-1, 0.296832, 0, -1, 0.437704,-99) , 
7, 0.124491, 1, 0, 0.467895,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.123613);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 169.39, 0, 1, 0.601258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.172873,-99) , 
3, 57.6398, 0, 0, 0.564055,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237985,-99) , 
6, 121.738, 0, 0, 0.4498,-99) , 
NN(
0, 
0, 
-1, 0.784989, 1, -1, 0.143407,-99) , 
5, 49.7914, 1, 0, 0.340468,-99) , 
0, 126.534, 1, 0, 0.476794,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.147153);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 66.3686, 1, 1, 0.865669,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254082,-99) , 
5, 53.7707, 1, 0, 0.489498,-99) , 
0, 184.816, 0, 0, 0.55921,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.77193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421553,-99) , 
12, 0.290633, 0, 0, 0.651006,-99) , 
NN(
0, 
0, 
-1, 0.543484, 0, -1, 0.302273,-99) , 
7, 0.468084, 1, 0, 0.387035,-99) , 
2, 2.03188, 1, 0, 0.480248,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.19128);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.26669,-99) , 
6, 97.3392, 0, 0, 0.605199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0336403,-99) , 
1, 2.98385, 1, 0, 0.554403,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254995,-99) , 
15, 0.655713, 0, 0, 0.470847,-99) , 
NN(
0, 
0, 
-1, 0.686208, 1, -1, 0.267353,-99) , 
5, 29.0621, 1, 0, 0.343874,-99) , 
10, 1.4612, 1, 0, 0.427495,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.103542);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 56.4424, 0, 1, 0.771239,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354878,-99) , 
9, 2.1069, 1, 0, 0.487203,-99) , 
NN(
0, 
0, 
-1, 1.52963, 0, -1, 0.343644,-99) , 
1, 1.91802, 1, 0, 0.43169,-99) , 
12, 0.0628672, 1, 0, 0.451155,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.188235);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.129633,-99) , 
2, 2.75948, 1, 0, 0.649323,-99) , 
NN(
0, 
0, 
-1, 141.353, 1, -1, 0.428924,-99) , 
6, 114.397, 0, 0, 0.535451,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321398,-99) , 
8, 0.964254, 1, 0, 0.490246,-99) , 
NN(
0, 
0, 
-1, 3.44808, 0, -1, 0.106106,-99) , 
1, 2.06423, 1, 0, 0.345075,-99) , 
6, 146.402, 1, 0, 0.484392,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.108906);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.97995, 0, 1, 0.893242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47623,-99) , 
5, 28.9415, 0, 0, 0.772758,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.832344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484044,-99) , 
10, 0.916428, 1, 0, 0.536177,-99) , 
NN(
0, 
0, 
-1, 137.064, 1, -1, 0.336524,-99) , 
12, 0.93065, 1, 0, 0.447223,-99) , 
3, 41.2759, 1, 0, 0.510367,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0955334);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30869,-99) , 
15, 0.955083, 1, 0, 0.546609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 79.2646, 0, 0, 0.531787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 206.9, 1, 0, 0.51765,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0428057);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.964265,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.972227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47727,-99) , 
4, 2.87933, 1, 0, 0.786082,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29889,-99) , 
0, 125.253, 1, 0, 0.436345,-99) , 
12, 0.0943207, 1, 0, 0.465308,-99) , 
1, 3.67154, 0, 0, 0.496627,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.075792);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.34256, 1, 1, 0.633577,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362785,-99) , 
12, 0.525987, 0, 0, 0.474981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0928107,-99) , 
4, 3.6967, 0, 0, 0.216296,-99) , 
3, 82.0913, 0, 0, 0.408864,-99) , 
13, 1.58823, 1, 0, 0.508177,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0893767);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.921973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290665,-99) , 
10, 2.42891, 0, 0, 0.775196,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416121,-99) , 
11, 1.08936, 1, 0, 0.494164,-99) , 
NN(
0, 
0, 
-1, 0.371345, 1, -1, 0.224711,-99) , 
0, 141.262, 1, 0, 0.449565,-99) , 
1, 3.1692, 0, 0, 0.499657,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0945928);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.85744, 0, 1, 0.636716,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.228423,-99) , 
0, 105.919, 0, 0, 0.456109,-99) , 
15, 0.820378, 1, 0, 0.557296,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.163181,-99) , 
6, 129.666, 1, 0, 0.372461,-99) , 
NN(
0, 
0, 
-1, 2.03509, 1, -1, 0.0731491,-99) , 
4, 3.37438, 1, 0, 0.250719,-99) , 
14, 0.870331, 0, 0, 0.516224,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.110794);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.935114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466697,-99) , 
1, 2.09376, 1, 0, 0.750459,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403441,-99) , 
0, 108.523, 0, 0, 0.525161,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167973,-99) , 
10, 1.00695, 1, 0, 0.315192,-99) , 
0, 130.182, 1, 0, 0.463034,-99) , 
12, 0.0943514, 1, 0, 0.483648,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0761537);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440233,-99) , 
4, 2.78616, 0, 0, 0.560484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208786,-99) , 
3, 112.847, 0, 0, 0.338994,-99) , 
14, 0.869722, 0, 0, 0.532661,-99) , 
NN(
0, 
0, 
-1, 33.0032, 1, -1, 0.185884,-99) , 
11, 2.76272, 1, 0, 0.508303,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0627892);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195386,-99) , 
0, 87.3884, 0, 0, 0.614113,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227474,-99) , 
12, 0.933966, 1, 0, 0.388998,-99) , 
5, 37.0245, 1, 0, 0.508636,-99) , 
NN(
0, 
0, 
-1, 1.84535, 1, -1, 0.214132,-99) , 
8, 2.61427, 1, 0, 0.476285,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0118146);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.936995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306307,-99) , 
6, 132.299, 1, 0, 0.760742,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257879,-99) , 
15, 0.962596, 1, 0, 0.49098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0874893,-99) , 
9, 0.214242, 0, 0, 0.470942,-99) , 
9, 2.92057, 0, 0, 0.507593,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.087287);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.828583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.758404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.201753,-99) , 
3, 78.9128, 1, 0, 0.555798,-99) , 
2, 1.97865, 1, 0, 0.68239,-99) , 
NN(
0, 
0, 
-1, 133.116, 1, -1, 0.380161,-99) , 
9, 0.595172, 1, 0, 0.430709,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.083627);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 140.637, 1, 1, 0.843559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.17328,-99) , 
6, 143.596, 1, 0, 0.714366,-99) , 
NN(
NN(
0, 
0, 
-1, 42.5665, 1, 1, 0.647269,-99) , 
NN(
0, 
0, 
-1, 169.38, 1, -1, 0.411712,-99) , 
9, 0.971362, 1, 0, 0.487882,-99) , 
10, 0.694859, 1, 0, 0.526391,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0539497);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.832107,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.761739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48219,-99) , 
2, 3.1973, 0, 0, 0.50816,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0779335,-99) , 
11, 0.422164, 1, 0, 0.212865,-99) , 
1, 2.72682, 1, 0, 0.468577,-99) , 
11, 3.04957, 0, 0, 0.499268,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.183297);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349728,-99) , 
14, 0.898549, 0, 0, 0.585339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216943,-99) , 
8, 2.21389, 0, 0, 0.322129,-99) , 
2, 1.29242, 0, 0, 0.533388,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.796225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402245,-99) , 
14, 0.959143, 0, 0, 0.588906,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0924477,-99) , 
10, 2.3956, 0, 0, 0.245802,-99) , 
7, 0.438217, 1, 0, 0.346582,-99) , 
6, 158.322, 1, 0, 0.485003,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.127151);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.8512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460335,-99) , 
7, 0.742206, 1, 0, 0.740396,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375588,-99) , 
14, 0.958885, 0, 0, 0.512777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244205,-99) , 
2, 2.84697, 0, 0, 0.30056,-99) , 
5, 33.8863, 1, 0, 0.402744,-99) , 
2, 1.11034, 1, 0, 0.450339,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0643181);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.953761, 1, 1, 0.752003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361508,-99) , 
6, 147.417, 1, 0, 0.660635,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405476,-99) , 
7, 0.683962, 1, 0, 0.473873,-99) , 
NN(
0, 
0, 
-1, 1.93256, 1, -1, 0.0568018,-99) , 
0, 158.179, 1, 0, 0.444112,-99) , 
10, 0.684139, 1, 0, 0.482089,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.067454);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.833923,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367548,-99) , 
11, 2.7192, 1, 0, 0.654804,-99) , 
NN(
0, 
0, 
-1, 0.959184, 0, -1, 0.425659,-99) , 
10, 0.684191, 1, 0, 0.47155,-99) , 
7, 0.0956858, 1, 0, 0.50154,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0875368);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.845744,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.210472,-99) , 
14, 0.870208, 0, 0, 0.507405,-99) , 
5, 9.89149, 1, 0, 0.533022,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.193934,-99) , 
5, 46.4993, 1, 0, 0.404151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 2.05129, 1, 0, 0.309979,-99) , 
6, 166.602, 1, 0, 0.493513,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.133211);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.02934, 1, 1, 0.878023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413355,-99) , 
4, 2.91584, 0, 0, 0.80447,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.800137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437013,-99) , 
3, 104.523, 0, 0, 0.706737,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406547,-99) , 
8, 0.379519, 1, 0, 0.444571,-99) , 
13, 2.92433, 0, 0, 0.477197,-99) , 
0, 183.662, 0, 0, 0.538717,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0341973);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278721,-99) , 
8, 0.161327, 0, 0, 0.580566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.222854,-99) , 
14, 0.932458, 1, 0, 0.324312,-99) , 
2, 1.35952, 0, 0, 0.534719,-99) , 
NN(
0, 
0, 
-1, 0.815974, 1, -1, 0.217068,-99) , 
0, 159.731, 1, 0, 0.508296,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0465981);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471575,-99) , 
14, 0.975448, 0, 0, 0.566603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304002,-99) , 
14, 0.935104, 1, 0, 0.402266,-99) , 
6, 115.56, 0, 0, 0.502296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 168.165, 1, 0, 0.479143,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.117947);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 187.069, 0, 1, 0.801267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292091,-99) , 
15, 0.322034, 0, 0, 0.733622,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432173,-99) , 
14, 0.965429, 1, 0, 0.517805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 2.96854, 1, 0, 0.492237,-99) , 
4, 3.48205, 0, 0, 0.541656,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.118659);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.738447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443223,-99) , 
1, 2.74613, 1, 0, 0.689549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.217614,-99) , 
15, 0.947627, 1, 0, 0.60792,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289663,-99) , 
6, 116.406, 0, 0, 0.473449,-99) , 
NN(
0, 
0, 
-1, 0.820773, 1, -1, 0.296392,-99) , 
1, 1.31546, 0, 0, 0.419623,-99) , 
13, 0.873589, 1, 0, 0.461246,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.117891);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.886466,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.744782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414435,-99) , 
1, 1.41174, 0, 0, 0.60844,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.268262,-99) , 
7, 0.683495, 1, 0, 0.405191,-99) , 
1, 1.94803, 1, 0, 0.528184,-99) , 
4, 4.43478, 0, 0, 0.553316,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0426947);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.798098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.274974,-99) , 
9, 3.0297, 1, 0, 0.728513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 167.544, 1, 0, 0.532581,-99) , 
9, 2.64559, 0, 0, 0.582201,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.20006,-99) , 
6, 136.226, 1, 0, 0.428012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 117.554, 0, 0, 0.307269,-99) , 
3, 56.48, 0, 0, 0.552473,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.084565);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.729585, 1, 1, 0.926778,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.744381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311969,-99) , 
6, 131.888, 1, 0, 0.535287,-99) , 
7, 0.748066, 1, 0, 0.827655,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319398,-99) , 
4, 3.89452, 1, 0, 0.575754,-99) , 
NN(
0, 
0, 
-1, 1.7662, 1, -1, 0.381736,-99) , 
4, 3.16001, 0, 0, 0.444248,-99) , 
9, 2.82689, 0, 0, 0.522164,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0934935);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.80232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.234976,-99) , 
5, 31.6902, 0, 0, 0.694835,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.126423,-99) , 
15, 0.281549, 0, 0, 0.503938,-99) , 
1, 2.59598, 0, 0, 0.554292,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236999,-99) , 
14, 0.97278, 0, 0, 0.41158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0447135,-99) , 
4, 3.10171, 1, 0, 0.273925,-99) , 
8, 2.80048, 1, 0, 0.52964,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.113411);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.789257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393691,-99) , 
11, 0.308112, 0, 0, 0.714658,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198789,-99) , 
13, 0.838633, 1, 0, 0.418472,-99) , 
7, 1.95717, 1, 0, 0.649993,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.827988,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328643,-99) , 
13, 1.18352, 1, 0, 0.384617,-99) , 
8, 0.0702116, 1, 0, 0.419495,-99) , 
14, 0.99683, 0, 0, 0.484789,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0249313);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.850069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.19965,-99) , 
14, 0.857423, 0, 0, 0.537143,-99) , 
1, 0.971532, 1, 0, 0.571041,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.24023,-99) , 
15, 0.917816, 1, 0, 0.523594,-99) , 
NN(
0, 
0, 
-1, 0.911942, 0, -1, 0.265663,-99) , 
12, 0.768184, 0, 0, 0.370766,-99) , 
9, 2.4236, 1, 0, 0.51255,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.136516);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.955515, 0, 1, 0.806441,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.159801,-99) , 
8, 1.6158, 1, 0, 0.473038,-99) , 
15, 0.506075, 1, 0, 0.628683,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.827518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410942,-99) , 
3, 120.832, 0, 0, 0.50003,-99) , 
NN(
0, 
0, 
-1, 2.24477, 1, -1, 0.249251,-99) , 
5, 32.6481, 1, 0, 0.38816,-99) , 
12, 1.05731, 1, 0, 0.539726,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0759498);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471668,-99) , 
15, 0.49034, 0, 0, 0.604383,-99) , 
NN(
0, 
0, 
-1, 2.18289, 1, -1, 0.386501,-99) , 
15, 0.865351, 1, 0, 0.533258,-99) , 
NN(
0, 
0, 
-1, 74.9409, 1, -1, 0.190831,-99) , 
4, 3.64268, 1, 0, 0.501077,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0986071);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.851131,-99) , 
NN(
NN(
0, 
0, 
-1, 2.59031, 0, 1, 0.697179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382364,-99) , 
12, 0.218362, 1, 0, 0.422703,-99) , 
9, 2.8288, 0, 0, 0.467995,-99) , 
11, 3.04979, 0, 0, 0.513739,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0785828);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.882736,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409064,-99) , 
9, 2.58502, 1, 0, 0.547176,-99) , 
NN(
0, 
0, 
-1, 1.96486, 1, -1, 0.304585,-99) , 
11, 2.29837, 1, 0, 0.520883,-99) , 
11, 3.01845, 0, 0, 0.553866,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0894988);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.886482,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485744,-99) , 
4, 2.89017, 1, 0, 0.586049,-99) , 
NN(
0, 
0, 
-1, 0.188872, 0, -1, 0.337094,-99) , 
0, 123.135, 1, 0, 0.481837,-99) , 
11, 3.04648, 0, 0, 0.507992,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0452496);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.845124,-99) , 
NN(
NN(
0, 
0, 
-1, 0.348904, 1, 1, 0.542334,-99) , 
NN(
0, 
0, 
-1, 1.84122, 1, -1, 0.0772752,-99) , 
1, 2.89092, 1, 0, 0.513257,-99) , 
4, 4.33476, 0, 0, 0.541399,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.117957);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.876113,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34238,-99) , 
5, 54.0941, 1, 0, 0.531365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153099,-99) , 
15, 0.633032, 0, 0, 0.33596,-99) , 
14, 0.901719, 0, 0, 0.492307,-99) , 
4, 4.59529, 0, 0, 0.516808,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0660284);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.721855, 1, 1, 0.870891,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35767,-99) , 
6, 115.761, 1, 0, 0.46794,-99) , 
1, 2.46347, 0, 0, 0.677554,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431271,-99) , 
4, 3.44602, 0, 0, 0.470565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.082461,-99) , 
0, 161.809, 1, 0, 0.443626,-99) , 
15, 0.409038, 1, 0, 0.514989,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.119171);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422629,-99) , 
2, 2.86801, 1, 0, 0.709677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.21545,-99) , 
2, 1.53468, 0, 0, 0.63986,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.203939,-99) , 
14, 0.844302, 0, 0, 0.495471,-99) , 
NN(
0, 
0, 
-1, 105.114, 0, -1, 0.331803,-99) , 
15, 0.827877, 1, 0, 0.424706,-99) , 
12, 2.05122, 0, 0, 0.467332,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0681544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.82407, 0, 1, 0.60402,-99) , 
NN(
0, 
0, 
-1, 155.539, 1, -1, 0.4415,-99) , 
10, 2.05144, 1, 0, 0.538908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.149536,-99) , 
9, 0.192491, 0, 0, 0.521933,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.039479);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.950906,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209962,-99) , 
1, 2.984, 1, 0, 0.538206,-99) , 
NN(
0, 
0, 
-1, 3.04577, 1, -1, 0.176587,-99) , 
13, 0.252159, 0, 0, 0.513712,-99) , 
1, 3.66814, 0, 0, 0.536406,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0998442);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 176.51, 0, 1, 0.803687,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.779719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437223,-99) , 
3, 111.744, 0, 0, 0.571589,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.774969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370631,-99) , 
12, 0.0679732, 1, 0, 0.404621,-99) , 
7, 1.33591, 0, 0, 0.476444,-99) , 
3, 26.5006, 1, 0, 0.505088,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0837003);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.75015, 1, 1, 0.825079,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497537,-99) , 
9, 2.70644, 0, 0, 0.538363,-99) , 
0, 177.483, 0, 0, 0.577523,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.800691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330372,-99) , 
1, 2.34006, 0, 0, 0.443715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 140.544, 1, 0, 0.370049,-99) , 
6, 161.414, 1, 0, 0.538071,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.079882);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.869034,-99) , 
NN(
NN(
0, 
0, 
-1, 2.33533, 0, 1, 0.548211,-99) , 
NN(
0, 
0, 
-1, 103.946, 0, -1, 0.33921,-99) , 
12, 1.49246, 1, 0, 0.48309,-99) , 
7, 2.98426, 0, 0, 0.507814,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.105499);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.268931,-99) , 
5, 12.6539, 0, 0, 0.668513,-99) , 
NN(
0, 
0, 
-1, 2.96091, 0, -1, 0.223626,-99) , 
11, 2.80079, 1, 0, 0.614414,-99) , 
NN(
NN(
0, 
0, 
-1, 0.408795, 1, 1, 0.676189,-99) , 
NN(
0, 
0, 
-1, 1.33828, 1, -1, 0.323196,-99) , 
10, 2.86053, 0, 0, 0.427193,-99) , 
10, 1.71183, 1, 0, 0.515379,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.052125);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.907994,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624626,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283149,-99) , 
1, 1.73692, 1, 0, 0.474211,-99) , 
15, 0.314609, 0, 0, 0.704586,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.781122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360257,-99) , 
6, 130.513, 1, 0, 0.662417,-99) , 
NN(
0, 
0, 
-1, 0.362956, 0, -1, 0.45701,-99) , 
10, 0.622014, 1, 0, 0.489705,-99) , 
15, 0.348904, 1, 0, 0.530858,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.116763);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.03755, 1, 1, 0.806856,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413229,-99) , 
5, 41.7835, 1, 0, 0.574626,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.739838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289039,-99) , 
2, 1.57799, 1, 0, 0.40928,-99) , 
4, 2.73809, 0, 0, 0.519358,-99) , 
7, 0.125855, 1, 0, 0.549408,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.137651);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.859156,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218212,-99) , 
8, 2.82705, 1, 0, 0.576451,-99) , 
12, 2.70375, 0, 0, 0.606724,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.83757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336472,-99) , 
3, 148.539, 0, 0, 0.387217,-99) , 
7, 2.91896, 0, 0, 0.441846,-99) , 
10, 1.09967, 0, 0, 0.558124,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.061417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.18154, 1, 1, 0.699834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0775484,-99) , 
1, 2.96614, 1, 0, 0.507111,-99) , 
11, 2.08502, 0, 0, 0.560266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 79.9862, 0, 0, 0.542748,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.172239);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.860282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469549,-99) , 
10, 0.775818, 0, 0, 0.785954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362307,-99) , 
5, 54.1659, 1, 0, 0.732761,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.782198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440373,-99) , 
14, 0.946235, 1, 0, 0.606307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271665,-99) , 
13, 2.87893, 0, 0, 0.354656,-99) , 
13, 1.93292, 1, 0, 0.471435,-99) , 
8, 2.27205, 0, 0, 0.539001,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0712996);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.402478, 1, 1, 0.63299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264242,-99) , 
8, 0.409892, 0, 0, 0.431529,-99) , 
5, 44.194, 0, 0, 0.507067,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.816127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293238,-99) , 
15, 0.580069, 0, 0, 0.524428,-99) , 
NN(
0, 
0, 
-1, 2.04012, 1, -1, 0.248141,-99) , 
14, 0.898426, 1, 0, 0.335154,-99) , 
8, 1.77482, 1, 0, 0.458988,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0398163);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.765618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448152,-99) , 
8, 2.82519, 1, 0, 0.700034,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360734,-99) , 
12, 1.21275, 1, 0, 0.523271,-99) , 
8, 2.20638, 0, 0, 0.581155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0660814,-99) , 
9, 3.0807, 1, 0, 0.561905,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.139167);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 131.454, 1, 1, 0.711034,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279839,-99) , 
1, 1.36515, 1, 0, 0.442055,-99) , 
0, 113.83, 0, 0, 0.61491,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0144024,-99) , 
0, 133.148, 1, 0, 0.491583,-99) , 
NN(
0, 
0, 
-1, 0.965211, 0, -1, 0.26963,-99) , 
6, 128.196, 1, 0, 0.373598,-99) , 
9, 1.96185, 1, 0, 0.514686,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0175214);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.16441,-99) , 
0, 84.0333, 0, 0, 0.533599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.126303,-99) , 
4, 1.5043, 0, 0, 0.510222,-99) , 
NN(
0, 
0, 
-1, 1.31076, 1, -1, 0.130322,-99) , 
0, 161.317, 1, 0, 0.483002,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0898418);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.32816, 1, 1, 0.801678,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438979,-99) , 
13, 0.590921, 1, 0, 0.566371,-99) , 
9, 1.64001, 0, 0, 0.640066,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803534,-99) , 
NN(
0, 
0, 
-1, 2.37745, 1, -1, 0.351229,-99) , 
8, 0.0625168, 1, 0, 0.383031,-99) , 
13, 1.74532, 1, 0, 0.49754,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0611669);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.806302,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.820086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404679,-99) , 
15, 0.55166, 0, 0, 0.704628,-99) , 
NN(
0, 
0, 
-1, 132.127, 1, -1, 0.417001,-99) , 
12, 2.55059, 0, 0, 0.457042,-99) , 
5, 9.7281, 1, 0, 0.490241,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.181966);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245437,-99) , 
12, 0.280042, 0, 0, 0.59303,-99) , 
NN(
0, 
0, 
-1, 2.2003, 1, -1, 0.143053,-99) , 
4, 2.06597, 0, 0, 0.554717,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365402,-99) , 
5, 25.4229, 1, 0, 0.415977,-99) , 
NN(
0, 
0, 
-1, 2.80279, 1, -1, 0.0955455,-99) , 
0, 92.0771, 0, 0, 0.348126,-99) , 
1, 1.57831, 0, 0, 0.477248,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.143465);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.97116, 0, 1, 0.75901,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.187707,-99) , 
14, 0.957657, 0, 0, 0.347996,-99) , 
13, 1.27271, 0, 0, 0.654385,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 85.9318, 0, 0, 0.526795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.222663,-99) , 
15, 0.372662, 1, 0, 0.306095,-99) , 
0, 124.923, 1, 0, 0.439613,-99) , 
8, 2.33113, 0, 0, 0.486693,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0448047);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39798,-99) , 
15, 0.468663, 0, 0, 0.514728,-99) , 
NN(
0, 
0, 
-1, 1.78191, 1, -1, 0.32902,-99) , 
2, 1.42889, 0, 0, 0.475027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.103563,-99) , 
0, 170.887, 1, 0, 0.45554,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0768926);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.866826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303115,-99) , 
4, 2.51858, 0, 0, 0.494679,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271653,-99) , 
11, 0.331965, 1, 0, 0.331861,-99) , 
15, 0.543474, 0, 0, 0.433884,-99) , 
11, 3.0465, 0, 0, 0.462721,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.113674);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476019,-99) , 
8, 0.750616, 1, 0, 0.541356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0975498,-99) , 
1, 2.9802, 1, 0, 0.518188,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.738234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345735,-99) , 
0, 128.678, 1, 0, 0.569532,-99) , 
NN(
0, 
0, 
-1, 0.493792, 0, -1, 0.140656,-99) , 
1, 2.20732, 0, 0, 0.314026,-99) , 
4, 3.34957, 1, 0, 0.475388,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0809133);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 178.619, 0, 1, 0.834153,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.727625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462349,-99) , 
14, 0.961817, 1, 0, 0.529238,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240305,-99) , 
8, 1.21858, 0, 0, 0.359425,-99) , 
14, 0.942805, 0, 0, 0.473508,-99) , 
3, 26.5583, 1, 0, 0.508213,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0260307);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.77343,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448753,-99) , 
1, 2.16782, 0, 0, 0.50159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 169.38, 1, 0, 0.480831,-99) , 
8, 0.0625185, 1, 0, 0.499404,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0751395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.888699,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498173,-99) , 
7, 0.901537, 1, 0, 0.581924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.159831,-99) , 
4, 3.83845, 1, 0, 0.561513,-99) , 
4, 4.61509, 0, 0, 0.582637,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0983701);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.0385, 1, 1, 0.81234,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.276993,-99) , 
13, 0.431935, 0, 0, 0.529919,-99) , 
NN(
0, 
0, 
-1, 105.426, 0, -1, 0.344724,-99) , 
10, 2.39707, 1, 0, 0.47099,-99) , 
1, 3.16947, 0, 0, 0.508061,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.104856);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.882436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456121,-99) , 
10, 2.42799, 0, 0, 0.740751,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.270662,-99) , 
2, 2.43898, 1, 0, 0.486399,-99) , 
NN(
0, 
0, 
-1, 1.99794, 0, -1, 0.256992,-99) , 
4, 3.26145, 1, 0, 0.427596,-99) , 
1, 3.1692, 0, 0, 0.454981,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0357678);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.21923, 1, 1, 0.8222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37611,-99) , 
6, 116.715, 0, 0, 0.718295,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444467,-99) , 
15, 0.955097, 0, 0, 0.473638,-99) , 
NN(
0, 
0, 
-1, 1.74913, 1, -1, 0.183407,-99) , 
2, 1.10799, 0, 0, 0.444598,-99) , 
10, 2.89229, 0, 0, 0.485051,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.115945);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.771404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380718,-99) , 
9, 1.12446, 0, 0, 0.710634,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190086,-99) , 
3, 117.095, 0, 0, 0.349792,-99) , 
4, 2.76644, 0, 0, 0.629327,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0974247,-99) , 
5, 53.2028, 1, 0, 0.501264,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.779862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227414,-99) , 
5, 89.2186, 0, 0, 0.307731,-99) , 
12, 0.622595, 0, 0, 0.434757,-99) , 
14, 0.993659, 0, 0, 0.501673,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0659823);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.85355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364393,-99) , 
15, 0.827852, 1, 0, 0.77315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0506083,-99) , 
1, 2.86712, 1, 0, 0.519872,-99) , 
13, 1.96181, 0, 0, 0.605924,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.734308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405629,-99) , 
2, 2.55783, 0, 0, 0.483824,-99) , 
NN(
0, 
0, 
-1, 0.461149, 1, -1, 0.102663,-99) , 
3, 73.2144, 0, 0, 0.411947,-99) , 
11, 1.24512, 0, 0, 0.502827,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.05613);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.96461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469383,-99) , 
6, 243.872, 0, 0, 0.811994,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405988,-99) , 
4, 2.28447, 1, 0, 0.436415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.810527, 0, 0, 0.421034,-99) , 
1, 3.16947, 0, 0, 0.459385,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0575067);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.883459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483399,-99) , 
10, 1.87366, 0, 0, 0.784915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245403,-99) , 
15, 0.265241, 0, 0, 0.691672,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4324,-99) , 
9, 1.7612, 1, 0, 0.502382,-99) , 
NN(
0, 
0, 
-1, 1.05745, 1, -1, 0.338145,-99) , 
9, 1.46246, 0, 0, 0.436803,-99) , 
15, 0.335008, 1, 0, 0.479756,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0479841);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 48.3008, 1, 1, 0.769894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.131416,-99) , 
9, 2.26607, 1, 0, 0.505294,-99) , 
9, 2.49291, 0, 0, 0.565616,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.907468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452785,-99) , 
9, 1.35899, 1, 0, 0.657916,-99) , 
NN(
0, 
0, 
-1, 100.931, 0, -1, 0.382143,-99) , 
5, 65.9135, 0, 0, 0.435512,-99) , 
8, 1.40142, 0, 0, 0.497814,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0594374);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.791991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476029,-99) , 
6, 118.944, 0, 0, 0.680415,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.187464,-99) , 
7, 0.402733, 1, 0, 0.366482,-99) , 
5, 69.3979, 1, 0, 0.619521,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.164684,-99) , 
0, 149.974, 1, 0, 0.479673,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.205366,-99) , 
7, 2.80064, 0, 0, 0.259063,-99) , 
12, 1.30645, 1, 0, 0.394111,-99) , 
3, 122.521, 0, 0, 0.484982,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0723159);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 250.536, 0, 1, 0.812242,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499986,-99) , 
5, 44.4989, 0, 0, 0.560744,-99) , 
NN(
0, 
0, 
-1, 2.32908, 1, -1, 0.24716,-99) , 
7, 2.79754, 1, 0, 0.534978,-99) , 
1, 3.1692, 0, 0, 0.569436,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0662373);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.900298,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438394,-99) , 
10, 2.456, 1, 0, 0.575435,-99) , 
4, 4.29887, 0, 0, 0.598899,-99) , 
NN(
0, 
0, 
-1, 166.08, 0, -1, 0.232114,-99) , 
1, 1.08926, 0, 0, 0.571697,-99)    );
  // itree = 102
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.894747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48915,-99) , 
10, 0.354192, 1, 0, 0.518485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230903,-99) , 
9, 1.45557, 0, 0, 0.304867,-99) , 
11, 2.27171, 1, 0, 0.478972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 167.905, 1, 0, 0.456168,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0198348);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.601574, 1, 1, 0.587256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 3.03892, 1, 0, 0.56869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.855274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498164,-99) , 
9, 1.9113, 0, 0, 0.690298,-99) , 
NN(
0, 
0, 
-1, 2.82928, 0, -1, 0.190896,-99) , 
2, 2.60007, 0, 0, 0.340329,-99) , 
8, 2.42718, 1, 0, 0.526794,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0745227);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 35.1352, 0, 1, 0.661251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.143205,-99) , 
15, 0.259285, 0, 0, 0.63582,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 154.79, 1, 0, 0.466406,-99) , 
NN(
0, 
0, 
-1, 1.71786, 1, -1, 0.117501,-99) , 
15, 0.988199, 1, 0, 0.423104,-99) , 
15, 0.701364, 1, 0, 0.535292,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.0693622);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 43.8647, 1, 1, 0.867096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425711,-99) , 
10, 1.86498, 0, 0, 0.779018,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.770522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449079,-99) , 
4, 3.05083, 1, 0, 0.650968,-99) , 
NN(
0, 
0, 
-1, 41.8251, 0, -1, 0.441422,-99) , 
2, 1.3147, 1, 0, 0.481639,-99) , 
1, 2.9385, 0, 0, 0.533148,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0546307);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.81041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431086,-99) , 
12, 1.83673, 1, 0, 0.709788,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.730502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451682,-99) , 
10, 0.80853, 1, 0, 0.500134,-99) , 
8, 2.45934, 0, 0, 0.552966,-99) , 
NN(
0, 
0, 
-1, 0.536972, 1, -1, 0.22395,-99) , 
11, 2.60972, 1, 0, 0.522707,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0977526);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271172,-99) , 
1, 1.14923, 0, 0, 0.589992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.144426,-99) , 
10, 1.77252, 0, 0, 0.308296,-99) , 
5, 13.6872, 0, 0, 0.562484,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202332,-99) , 
6, 139.955, 1, 0, 0.416074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.036798,-99) , 
3, 138.495, 0, 0, 0.28854,-99) , 
5, 68.8065, 1, 0, 0.535339,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0222645);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.873074,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291342,-99) , 
7, 0.124402, 0, 0, 0.551165,-99) , 
NN(
0, 
0, 
-1, 0.516987, 1, -1, 0.193367,-99) , 
0, 169.817, 1, 0, 0.53018,-99) , 
11, 3.01847, 0, 0, 0.556861,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0789479);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.794369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475405,-99) , 
6, 162.886, 1, 0, 0.694953,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.877827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403445,-99) , 
12, 0.155182, 1, 0, 0.462259,-99) , 
8, 0.655072, 1, 0, 0.568556,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2084,-99) , 
8, 0.997552, 0, 0, 0.474192,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.127853,-99) , 
4, 3.10983, 0, 0, 0.249784,-99) , 
14, 0.984158, 1, 0, 0.388674,-99) , 
3, 113.72, 0, 0, 0.471351,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0718152);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.76011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456484,-99) , 
2, 2.28139, 1, 0, 0.674043,-99) , 
NN(
0, 
0, 
-1, 1.40991, 0, -1, 0.330868,-99) , 
0, 103.835, 0, 0, 0.595069,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.715183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354467,-99) , 
6, 210.068, 0, 0, 0.390392,-99) , 
NN(
0, 
0, 
-1, 1.16434, 1, -1, 0.0639925,-99) , 
0, 148.797, 1, 0, 0.346425,-99) , 
8, 1.2173, 1, 0, 0.48262,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.110198);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.610461, 0, 1, 0.804645,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208487,-99) , 
4, 3.04341, 1, 0, 0.44015,-99) , 
6, 123.955, 0, 0, 0.674228,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.835048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358001,-99) , 
3, 106.296, 0, 0, 0.681861,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374929,-99) , 
3, 161.408, 0, 0, 0.412661,-99) , 
9, 2.92592, 0, 0, 0.441932,-99) , 
10, 2.86049, 0, 0, 0.482456,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0380826);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.851051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363412,-99) , 
3, 78.1157, 1, 0, 0.752485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.819503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486136,-99) , 
13, 0.34541, 1, 0, 0.509996,-99) , 
0, 175.268, 0, 0, 0.541922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0758936,-99) , 
13, 0.134608, 0, 0, 0.507697,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.123122);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.154344, 0, 1, 0.819829,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.840973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420946,-99) , 
8, 2.18995, 0, 0, 0.539535,-99) , 
10, 2.12308, 1, 0, 0.645848,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.78294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314796,-99) , 
9, 1.473, 0, 0, 0.654584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237813,-99) , 
1, 1.92609, 1, 0, 0.39605,-99) , 
10, 0.663917, 1, 0, 0.45667,-99) , 
7, 0.715013, 1, 0, 0.535411,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0594191);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.955345, 1, 1, 0.86654,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.116088,-99) , 
10, 0.584335, 1, 0, 0.434133,-99) , 
10, 1.09967, 0, 0, 0.722371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.756435,-99) , 
NN(
0, 
0, 
-1, 176.134, 1, -1, 0.477535,-99) , 
12, 0.0621208, 1, 0, 0.502969,-99) , 
11, 2.08333, 0, 0, 0.565222,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.133881);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264004,-99) , 
4, 1.52385, 0, 0, 0.56575,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
13, 2.02713, 1, 0, 0.317787,-99) , 
3, 46.7154, 0, 0, 0.539639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0913248,-99) , 
6, 57.1514, 0, 0, 0.522508,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.114145);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.68217, 1, 1, 0.859641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.724371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422175,-99) , 
13, 2.15447, 1, 0, 0.570112,-99) , 
9, 2.79825, 0, 0, 0.629525,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.853607,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350786,-99) , 
8, 0.717261, 1, 0, 0.421416,-99) , 
11, 3.04961, 0, 0, 0.456275,-99) , 
7, 0.714504, 1, 0, 0.516889,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0529727);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295981,-99) , 
7, 0.279533, 0, 0, 0.631845,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183018,-99) , 
11, 2.80073, 1, 0, 0.579947,-99) , 
NN(
NN(
0, 
0, 
-1, 32.6032, 0, 1, 0.751281,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318019,-99) , 
7, 0.716233, 1, 0, 0.401876,-99) , 
3, 29.2628, 1, 0, 0.432111,-99) , 
10, 1.30558, 1, 0, 0.480192,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0849867);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.836686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443572,-99) , 
9, 1.08895, 0, 0, 0.746485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.256386,-99) , 
15, 0.865873, 1, 0, 0.690215,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.751755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466837,-99) , 
5, 34.8516, 1, 0, 0.607094,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.68976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357834,-99) , 
6, 221.324, 0, 0, 0.413165,-99) , 
14, 0.993645, 0, 0, 0.474821,-99) , 
1, 2.70348, 0, 0, 0.519278,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0701085);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.914519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496246,-99) , 
15, 0.386699, 1, 0, 0.796485,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.172711,-99) , 
15, 0.992514, 1, 0, 0.528406,-99) , 
NN(
0, 
0, 
-1, 0.771352, 0, -1, 0.318476,-99) , 
2, 1.45843, 0, 0, 0.483802,-99) , 
1, 3.16436, 0, 0, 0.512319,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0530375);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.310667, 0, 1, 0.804552,-99) , 
NN(
NN(
0, 
0, 
-1, 0.395997, 1, 1, 0.76082,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.77264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425179,-99) , 
5, 10.9727, 1, 0, 0.448201,-99) , 
12, 0.156172, 1, 0, 0.474467,-99) , 
10, 2.89153, 0, 0, 0.516012,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0577987);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.886274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264372,-99) , 
1, 2.96057, 1, 0, 0.549172,-99) , 
11, 2.98735, 0, 0, 0.56606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0479978,-99) , 
7, 3.07744, 1, 0, 0.546489,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0151421);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.23214, 1, 1, 0.902418,-99) , 
NN(
NN(
0, 
0, 
-1, 2.2653, 0, 1, 0.584471,-99) , 
NN(
0, 
0, 
-1, 163.344, 1, -1, 0.414118,-99) , 
7, 0.683442, 1, 0, 0.481839,-99) , 
5, 10.6797, 1, 0, 0.511408,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.119267);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.829709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482041,-99) , 
4, 2.89378, 0, 0, 0.762884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253475,-99) , 
1, 2.39849, 0, 0, 0.677547,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400034,-99) , 
14, 0.933584, 0, 0, 0.511194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.104351,-99) , 
4, 3.74132, 1, 0, 0.495538,-99) , 
3, 57.2725, 1, 0, 0.531808,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0233957);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 191.065, 0, 1, 0.58112,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701576,-99) , 
NN(
0, 
0, 
-1, 0.843695, 0, -1, 0.326306,-99) , 
13, 2.79972, 0, 0, 0.377172,-99) , 
2, 2.4543, 1, 0, 0.522478,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0958739);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.51528, 0, 1, 0.738357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.872529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431946,-99) , 
1, 3.29478, 0, 0, 0.475676,-99) , 
14, 0.980935, 0, 0, 0.554739,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218801,-99) , 
6, 153.184, 1, 0, 0.496876,-99) , 
NN(
0, 
0, 
-1, 0.657937, 1, -1, 0.191055,-99) , 
5, 39.3214, 1, 0, 0.375994,-99) , 
15, 0.693174, 1, 0, 0.475213,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0312057);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 108.223, 0, 1, 0.764005,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.192204,-99) , 
14, 0.831593, 0, 0, 0.504972,-99) , 
8, 0.428928, 1, 0, 0.539198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.663652,-99) , 
NN(
0, 
0, 
-1, 37.0169, 0, -1, 0.148825,-99) , 
5, 66.6504, 0, 0, 0.28607,-99) , 
8, 0.22345, 0, 0, 0.511589,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.127216);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469424,-99) , 
5, 25.5009, 0, 0, 0.670496,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.217933,-99) , 
1, 2.11155, 0, 0, 0.351357,-99) , 
0, 101.239, 0, 0, 0.603169,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.842435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472525,-99) , 
2, 1.69974, 0, 0, 0.639173,-99) , 
NN(
0, 
0, 
-1, 154.605, 1, -1, 0.381117,-99) , 
12, 0.218362, 1, 0, 0.435056,-99) , 
4, 3.03488, 0, 0, 0.514256,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.108956);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.908498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46883,-99) , 
7, 2.30868, 1, 0, 0.745033,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0815541,-99) , 
1, 2.51021, 1, 0, 0.45825,-99) , 
7, 2.05019, 0, 0, 0.560564,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.269276,-99) , 
15, 0.561375, 0, 0, 0.503897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.220402,-99) , 
15, 0.970059, 0, 0, 0.300213,-99) , 
14, 0.961956, 1, 0, 0.381555,-99) , 
6, 121.055, 0, 0, 0.485015,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0249769);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.92822, 1, 1, 0.760285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357876,-99) , 
9, 2.58576, 1, 0, 0.689753,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458144,-99) , 
6, 96.8718, 1, 0, 0.507309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.135347,-99) , 
1, 2.99247, 1, 0, 0.489597,-99) , 
5, 55.4799, 0, 0, 0.535359,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0775745);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.749295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.234077,-99) , 
10, 2.19373, 1, 0, 0.671574,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399846,-99) , 
3, 133.89, 0, 0, 0.470666,-99) , 
8, 2.2424, 0, 0, 0.518923,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.21731,-99) , 
14, 0.941816, 0, 0, 0.400458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
14, 0.961956, 1, 0, 0.266226,-99) , 
0, 147.678, 1, 0, 0.488999,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0383406);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.817925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264977,-99) , 
4, 2.93469, 0, 0, 0.73685,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32797,-99) , 
12, 2.89252, 1, 0, 0.545956,-99) , 
0, 161.566, 0, 0, 0.584202,-99) , 
NN(
0, 
0, 
-1, 2.1809, 0, -1, 0.206779,-99) , 
0, 91.6046, 0, 0, 0.561527,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0268342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.962632, 0, 1, 0.600975,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728917,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304378,-99) , 
14, 0.996857, 0, 0, 0.352186,-99) , 
5, 10.3904, 1, 0, 0.395213,-99) , 
8, 1.18622, 1, 0, 0.495554,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0877589);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.895914,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261728,-99) , 
10, 2.33166, 1, 0, 0.616896,-99) , 
4, 3.97665, 0, 0, 0.680776,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375363,-99) , 
9, 2.24298, 1, 0, 0.484325,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183852,-99) , 
1, 1.55911, 1, 0, 0.299676,-99) , 
7, 2.08266, 1, 0, 0.44263,-99) , 
1, 2.51851, 0, 0, 0.501718,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.00888522);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.867386,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.676338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457702,-99) , 
13, 2.76941, 0, 0, 0.494522,-99) , 
0, 166.26, 0, 0, 0.519024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.150872,-99) , 
0, 181.846, 1, 0, 0.503328,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.112927);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.764032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.281116,-99) , 
1, 1.15658, 0, 0, 0.687266,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407184,-99) , 
14, 0.949397, 1, 0, 0.473404,-99) , 
2, 1.48069, 1, 0, 0.516928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195763,-99) , 
2, 0.832277, 0, 0, 0.501188,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0615295);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.06384, 0, 1, 0.702259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249389,-99) , 
14, 0.858374, 0, 0, 0.664223,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.788264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391899,-99) , 
12, 1.28608, 1, 0, 0.68911,-99) , 
NN(
0, 
0, 
-1, 88.3331, 0, -1, 0.391911,-99) , 
9, 0.74976, 1, 0, 0.439976,-99) , 
7, 2.05154, 0, 0, 0.516432,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0644909);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.28386, 0, 1, 0.810382,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382786,-99) , 
3, 103.404, 0, 0, 0.533874,-99) , 
12, 2.51961, 0, 0, 0.609606,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387875,-99) , 
10, 1.37033, 1, 0, 0.475911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0396025,-99) , 
11, 2.48957, 1, 0, 0.42039,-99) , 
5, 40.9948, 1, 0, 0.540691,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0563172);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.30092, 1, 1, 0.783683,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.21557,-99) , 
8, 2.09208, 1, 0, 0.499117,-99) , 
10, 1.77196, 0, 0, 0.610868,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462656,-99) , 
12, 0.231458, 1, 0, 0.508452,-99) , 
NN(
0, 
0, 
-1, 2.025, 1, -1, 0.0681261,-99) , 
0, 151.333, 1, 0, 0.475954,-99) , 
7, 1.89491, 0, 0, 0.523336,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.0935941);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.64469, 1, 1, 0.834197,-99) , 
NN(
0, 
0, 
-1, 0.798925, 1, -1, 0.33507,-99) , 
10, 0.782626, 0, 0, 0.726538,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.781019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475117,-99) , 
6, 130.738, 1, 0, 0.56484,-99) , 
NN(
0, 
0, 
-1, 1.70763, 0, -1, 0.328555,-99) , 
6, 114.077, 0, 0, 0.48169,-99) , 
8, 2.18004, 0, 0, 0.566641,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0357647);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 33.4002, 1, 1, 0.69785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44794,-99) , 
11, 0.437042, 1, 0, 0.505104,-99) , 
8, 2.36219, 0, 0, 0.550417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.132789,-99) , 
4, 4.1437, 1, 0, 0.535784,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0842166);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.625009, 1, 1, 0.563935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240195,-99) , 
9, 0.295461, 0, 0, 0.542165,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.762309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3426,-99) , 
2, 1.60257, 1, 0, 0.449926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0935165,-99) , 
11, 0.282425, 0, 0, 0.307864,-99) , 
8, 0.406331, 0, 0, 0.487629,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0499655);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.952319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401964,-99) , 
10, 1.23213, 0, 0, 0.792665,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.768274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482529,-99) , 
0, 125.501, 1, 0, 0.687555,-99) , 
NN(
0, 
0, 
-1, 0.310977, 0, -1, 0.394484,-99) , 
3, 146.595, 0, 0, 0.44958,-99) , 
11, 2.95343, 0, 0, 0.489079,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.107324);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.77487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453961,-99) , 
3, 77.5403, 0, 0, 0.728279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395759,-99) , 
9, 0.814421, 1, 0, 0.485172,-99) , 
9, 2.33134, 0, 0, 0.578578,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.148254,-99) , 
6, 100.105, 0, 0, 0.458666,-99) , 
NN(
0, 
0, 
-1, 0.566977, 0, -1, 0.196945,-99) , 
1, 1.32564, 0, 0, 0.387179,-99) , 
15, 0.730591, 1, 0, 0.488693,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0710724);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420781,-99) , 
6, 185.453, 1, 0, 0.576229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.177532,-99) , 
3, 24.5263, 0, 0, 0.560839,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.796807,-99) , 
NN(
0, 
0, 
-1, 44.416, 0, -1, 0.192945,-99) , 
9, 1.59066, 1, 0, 0.35117,-99) , 
1, 1.25941, 0, 0, 0.52517,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.144362);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.60214, 0, 1, 0.870609,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.272207,-99) , 
11, 0.994912, 1, 0, 0.487161,-99) , 
15, 0.432687, 1, 0, 0.660033,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 146.722, 1, 0, 0.519692,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241611,-99) , 
0, 142.094, 0, 0, 0.316085,-99) , 
5, 32.5765, 1, 0, 0.424819,-99) , 
5, 52.8393, 0, 0, 0.492455,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0441965);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.760237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491895,-99) , 
6, 115.684, 0, 0, 0.669758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.151353,-99) , 
11, 1.64878, 1, 0, 0.622905,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271035,-99) , 
8, 0.383147, 0, 0, 0.457891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 161.554, 1, 0, 0.436553,-99) , 
10, 2.42494, 0, 0, 0.493603,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0850043);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 53.2142, 0, 1, 0.582405,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293891,-99) , 
4, 2.56153, 1, 0, 0.392773,-99) , 
2, 1.35817, 0, 0, 0.549292,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655849,-99) , 
NN(
0, 
0, 
-1, 0.814311, 1, -1, 0.185453,-99) , 
12, 0.0714486, 1, 0, 0.295912,-99) , 
11, 0.251022, 0, 0, 0.503751,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0820066);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.916912,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.812434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286332,-99) , 
10, 1.2747, 1, 0, 0.605402,-99) , 
2, 1.33554, 1, 0, 0.730784,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.849379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448115,-99) , 
5, 48.1173, 1, 0, 0.729569,-99) , 
NN(
0, 
0, 
-1, 0.497952, 0, -1, 0.442998,-99) , 
6, 228.739, 0, 0, 0.473513,-99) , 
0, 186.4, 0, 0, 0.500277,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.0966308);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.721361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489555,-99) , 
7, 0.49747, 0, 0, 0.639019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.154565,-99) , 
15, 0.693434, 1, 0, 0.284088,-99) , 
10, 0.84068, 0, 0, 0.566058,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.852244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460753,-99) , 
0, 148.938, 0, 0, 0.664422,-99) , 
NN(
0, 
0, 
-1, 3.03229, 0, -1, 0.349896,-99) , 
13, 0.625058, 1, 0, 0.413463,-99) , 
1, 1.66633, 1, 0, 0.48368,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
